### ISSUE TITLE
Idea for app to show user best time to leave for destination

### ISSUE THREAD

**Issue by punkouter** [Microsoft/Windows-appsample-trafficapp#1]
This is very close to an app I have always wanted and thought about trying to make. The one thing that is missing is the ability to gather data over time. The idea is I would like to take two points and through the times 4PM and 7PM for example leave the app running and have it gather the estimated time to travel each minute. At 7PM I would like the ability to see this information in a graph.

The main point is it would tell me between two periods of time what time is the best time to leave work.

It seems the app almost does this. It just needs a place to store the data and way to show the results.

**Comment by KarlErickson** [comment]
That would be interesting! Sounds like a great way to extend the app.
