### ISSUE TITLE
Allow using of Binding like a base to custom markup extension for XAML at UWP apps

### ISSUE THREAD

**Issue by Makeloft** [Microsoft/Windows-appsample-trafficapp#4]
Allow using of Binding like a base to custom markup extension for XAML at UWP apps

my mail for details: makeman@tut.by

There is old lack of native XAML
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/7232264-add-markup-extensions-to-and-improve-winrt-xaml

I had seen new post [https://msdn.microsoft.com/en-us/windows/uwp/xaml-platform/customresource-markup-extension] and, of course, at first, I install latest version of Visual Studio and try to create custom extension for localization but described in article way with derive from CustomXamlResourceLoader class doesn't work :(

I still have compiler errors:
Cannot assign 'Localizing' into property 'Text', type must be assignable to 'String'
Type 'local:Localizing' is used like a markup extension but does not derive from MarkupExtension.

Second, please, see ABindingExtension class and read the article about it
http://makeloft.xyz/lessons/xaml/custom-binding-extensions

 public abstract class ABindingExtension : Binding, IValueConverter
    {
        protected ABindingExtension()
        {
            Source = Converter = this;
        }

        protected ABindingExtension(object source) // Source, RelativeSource, null for DataContext
        {
            var relativeSource = source as RelativeSource;
            if (relativeSource == null && source != null) Source = source;
            else RelativeSource = relativeSource;
            Converter = this;
        }

        public abstract object Convert(object value, Type targetType, object parameter, CultureInfo culture);

        public virtual object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

This class very good and memory safe alternative for classical MarkupExtension. This approach works even on old Windows Phone Silverlight where is not MarkupExtension class.

I tried to apply this way to UWP but there are two artificial limitations of XAML-parser.

Look at sample

    public abstract class ABindingExtension : Binding, IValueConverter
    {
        protected ABindingExtension()
        {
            Source = Converter = this;
        }

        protected ABindingExtension(object source) // Source, RelativeSource, null for DataContext
        {
            var relativeSource = source as RelativeSource;
            if (relativeSource == null && source != null) Source = source;
            else RelativeSource = relativeSource;
            Converter = this;
        }

        public abstract object Convert(object value, Type targetType, object parameter, string culture);

        public virtual object ConvertBack(object value, Type targetType, object parameter, string culture)
        {
            throw new NotImplementedException();
        }
    }

    public class Localizing : ABindingExtension
    {
        public override object Convert(object value, Type targetType, object parameter, string culture)
        {
            return "test"; // return value by key
        }
    }

For example
<Control>
   <Control.DataContext> // is object
      <Localizing/>             // called Convert method like expected!
   <Control.DataContext>
</Control>

output => Works fine! 
But

<TextBlock>
   <TextBlock.Text> // is string
      <Lokalizing/>
   <TextBlock.Text>
</TextBlock>

output => Cannot assign 'Localizing' into property 'Text', type must be assignable to 'String'

Also
<Control DataContext="{local:Localizing}"/>

output => Type 'local:Localizing' is used like a markup extension but does not derive from MarkupExtension.

Pease, check this artificial limitaions for Bindings becouse all works fine, but only XAML-preprocessor get errors!

P.S. May be you will be interested by SwichConverter and some other power improvements for XAML and MVVM

<Grid.Resources>
    <SwitchConverter x:Key="NumberSwitchConverter" Default="Hello">
        <Case Key="0" Value="Zero"/>
        <Case Key="1" Value="One"/>
    </SwitchConverter>
</Grid.Resources>
<TextBlock Text="{Binding Number, Converter={StaticResource NumberSwitchConverter}}"/>

Number==0 => out: Zero
Number==1 => out: One
Number==2 => out: Hello

Please, see code samples and Aero Framework library
https://onedrive.live.com/?authkey=%21AMT2QVotfWTReos&cid=C8D6E2F8053DDCFB&id=C8D6E2F8053DDCFB%2123902&parId=C8D6E2F8053DDCFB%2123896&action=locate

Thanks!

**Comment by KarlErickson** [comment]
These are interesting ideas, but they are outside the scope of this particular sample. You should post your comments to either [Windows Developer Feedback](https://wpdev.uservoice.com/) or the [Developing UWP Apps](https://social.msdn.microsoft.com/Forums/en-US/home?forum=wpdevelop) forum. Thanks!

**Comment by Makeloft** [comment]
Karl, thank for your reply! 
Yes, I understand that all this outside the scope of this particular sample :)
And I know that there is possibility to post feedback, but, for example, request for custom markup extensions on native xaml is very-very old... I think that mechanism of feedbacks is slow and is not works properly. I want to find any person who developing architecture of UWP and communicate with them directly. Do you know similar people? Can you try to find them?

Sinserely, Vladimir


04.04.2016, 21:01, "Karl Erickson" <notifications@github.com>:

**Comment by Makeloft** [comment]
P.S. I am really sure that I can provide to Microsoft some wonderful ideas how to improve XAML and related MVVM developing.

04.04.2016, 21:01, "Karl Erickson" <notifications@github.com>:

**Comment by KarlErickson** [comment]
You might also try posting on a comment on the Issues list for the [main UWP feature sample repo](https://github.com/Microsoft/Windows-universal-samples).

**Comment by Makeloft** [comment]
Thank, I opened new issue into this repo.

04.04.2016, 22:22, "Karl Erickson" <notifications@github.com>:

**Comment by Makeloft** [comment]
Hello, Karl, how are you?

I wrote you some time ago and suggested some improvements for xaml-developing :)
I try to create issue on GitHub 
[https://github.com/Microsoft/Windows-universal-samples] 
and Microsoft Connect program 
[https://connect.microsoft.com/VisualStudio/Feedback/Details/2557360], 
but there is not any reaction... as I expected.

Karl, can you try to find e-mail of people from Microsoft who developing XAML platform at current moment? I just want communicate directly.

Sincerely, Vladimir
makeman@tut.by

04.04.2016, 22:22, "Karl Erickson" <notifications@github.com>:

**Comment by KarlErickson** [comment]
Unfortunately, I cannot put you in direct contact with the product team, but rest assured that there are people reviewing all the feedback we receive through the various channels, even if they do not respond immediately. Another great way to provide feedback is to join the [Windows Insider](https://insider.windows.com/) program, install the latest Insider Preview build, and use the Feedback Hub app that comes with the preview build. With this app, all feedback is visible to other Insiders, who can vote and comment on ideas to make sure they get the right attention. Also, because you are interested in data binding, be sure to check out [What's New in Windows UI/UX for UWP Apps](https://channel9.msdn.com/Events/Build/2016/B853), where you will find demos of preview functionality, including binding improvements that might help address some of your concerns. Thanks!

**Comment by Makeloft** [comment]
Karl, thank you very much for participate!
I try this ways...

Sincerely, Vladimir

19.04.2016, 21:01, "Karl Erickson" <notifications@github.com>:
