### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by asjain** [Microsoft/Windows-appsample-trafficapp#7]
getting this error while building:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Validation error. error 80080204: App manifest validation error: Line 31, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="TrafficMonitor.TrafficMonitor" without ActivatableClassId in windows.activatableClass.inProcessServer.	TrafficApp	C:\Users\jainabhi\source\repos\Windows-appsample-trafficapp-MVVM\TrafficApp\bin\x86\Debug\AppxManifest.xml		

also this warning
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The element 'Package' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' has invalid child element 'Metadata' in namespace 'http://schemas.microsoft.com/developer/appx/2015/build'. List of possible elements expected: 'Extensions, ComExtensions' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10'.	Miscellaneous Files	C:\Users\jainabhi\source\repos\Windows-appsample-trafficapp-MVVM\TrafficApp\bin\x86\Debug\AppxManifest.xml	42

**Comment by KarlErickson** [comment]
Thanks for the report! I'll investigate.

**Comment by KarlErickson** [comment]
This is a known issue with background tasks, and it's currently under investigation. The workaround is to set your minimum target to 15063. I've updated the projects in this repo accordingly, so they should build now.
